### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by disc0018**
Allows a better dimming of the LED in the night

### CODE REVIEW

**Comment by prampec** [comment]
First of all something is missing from this patch: the blinkmicrosec() is defined, but not implemented.

Am I right, that you use this method to dim the status LED? This method is not meant for that. Software PWM is very cpu consuming, and in real time system, line ESP8266 wifi/web handling it is not recommended at all.
Instead, what I can imagine is to use analogWrite instead of digitalWrite in doBlink().
But I did not wanted to put that in the core code, as not all IO pins might be capable for analogWrite, and also PWM might be effected by other timer based things.
But I'm might too paranoid on that, and you can correct me, that alanogWrite() is safe to use on any ESP8266 and ESP32 hardware.

**Comment by disc0018** [comment]
> 
> 
> First of all something is missing from this patch: the blinkmicrosec() is defined, but not implemented.
> 
> Am I right, that you use this method to dim the status LED? This method is not meant for that. Software PWM is very cpu consuming, and in real time system, line ESP8266 wifi/web handling it is not recommended at all.
> Instead, what I can imagine is to use analogWrite instead of digitalWrite in doBlink().
> But I did not wanted to put that in the core code, as not all IO pins might be capable for analogWrite, and also PWM might be effected by other timer based things.
> But I'm might too paranoid on that, and you can correct me, that alanogWrite() is safe to use on any ESP8266 and ESP32 hardware.

Sorry, my Pullrequest for the IotWebConf.cpp failed. It is my first time on Github. The Pullrequest failed because of of the missing declarations in IotWebConf.h... But the Pullrequest of IotWebConf.h passed!?!
I have to learn more about pullrequests.....

I don´t want to do real PWM just on tiny little dimmed blink for the bedroom, your blink is limited to 1% dutycycle minimum. My blinkInternalmicrosec(5000, 5) allows e.g. 5ppm dutycycle and 5s interval.

**Comment by disc0018** [comment]
The pull request for IotWebConf.cpp fails because of the missing
declaration in IotWebConf.h.
But the pull request of  IotWebConf.h with the declaration was o.k..... Can
you help me?
The changes in IotWebConf.cpp needs the new declarations IotWebConf.cp...

the missing code in IotWebConf.cpp is very simple and is far away from
PWM....

replace your this->blinkInternal(8000,2); with
this->blinkInternalmicrosec(5000, 5);
....
add code blinkmicrosec:
void IotWebConf::blinkmicrosec (uint64_t repeatMs, uint64_t
dutyCyclePerMillion)
{
  if (repeatMs == 0)
  {
    this->_blinkOnMs = this->_internalBlinkOnMs;
    this->_blinkOffMs = this->_internalBlinkOffMs;
  }
  else
  {
    this->_blinkOnMs = (repeatMs * dutyCyclePerMillion) / 1000000LL;
    this->_blinkOffMs = (repeatMs * (1000000LL - dutyCyclePerMillion)) /
1000000LL;
  }
}

void IotWebConf::blinkInternalmicrosec (unsigned long repeatMs, uint64_t
dutyCyclePerMillion)
{
  this->blinkmicrosec(repeatMs, dutyCyclePerMillion);
  this->_internalBlinkOnMs = this->_blinkOnMs;
  this->_internalBlinkOffMs = this->_blinkOffMs;
}


Am Mi., 26. Juni 2019 um 00:25 Uhr schrieb Balázs Kelemen <
notifications@github.com>:

**Comment by prampec** [comment]
Added this to version 2.2.1.

**Pull request closed without merging**
