### PR TITLE
Prevents wdt resets. Update IotWebConf.cpp

### PR DESCRIPTION
**Pull request by disc0018**
####Without this change the esp8266 does a wdt reset regularly.
The examples work, but more complicated code will quickly throw wdt resets. Maybe there is a better solution but that helped me. Additionally I have added more yield () commands in my loop ().

### CODE REVIEW

**Comment by prampec** [comment]
Thank you for the patch! Can you please include some reference about this yield() method in esp8266 context!?

**Comment by disc0018** [comment]
Sorry, this is my first time on GitHub. No idea how to provide reference on GitHub.

https://www.arduino.cc/en/Reference/SchedulerYield.




Gesendet von Mail für Windows 10

Von: Balázs Kelemen
Gesendet: Dienstag, 25. Juni 2019 17:12
An: prampec/IotWebConf
Cc: disc0018; Author
Betreff: Re: [prampec/IotWebConf] Prevents wdt resets. Update IotWebConf.cpp(#49)

Thank you for the patch! Can you please include some reference about this yield() method in esp8266 context!?

**Comment by prampec** [comment]
I'm not completely sure about this change.

First of all, I pretty much believe, that delay() on ESP8266 will eventually call yield(). So calling yield() after delay should not make any difference.

On the doLoop() ... it is not the responsibility of IotWebConf, to keep the system running. So if you are getting in trouble with wdt, you should call yield() in your code e.g. before calling iotWebConf.doLoop(). I also believe, that the parent method, that calls loop() in an infinit loop, also calls yield. Thus the only thing you should do is just let your loop method exit once in a while.

Can you please confirm this?!

**Comment by disc0018** [comment]
You are completly rigth delay should call yield.... I know.
And I admit your code is working standalone.
My code works with wifi standalone without problems.
In combination both produce timing problems.
I tested my code and your code intesivly.
Your code has only on "delay(1)" in your IotWebConf.
Is this enougth?
Perphaps 1ms delay is to short for e.g. wifi under many circumstances?
Is 1ms delay enough for calling yield()? I don´t know.
why yield() ->https://www.esp8266.com/viewtopic.php?f=32&t=10069

The only way to get my code working with yours without wdt reset was:
1. adding yield() in your doLoop().
2. removing 2 Tickers from my code, and call them via my loop() direktly;
3. my loop() is calling your doLoop() as frequent as possible.
4. my loop() includes 1 more yield();

Now it seems to work.
But I think the timing of your code should be more secure.
An Tickers are not the best idea to combine.

Yours Dirk








Am Mi., 26. Juni 2019 um 00:02 Uhr schrieb Balázs Kelemen <
notifications@github.com>:

**Comment by prampec** [comment]
I took a look at ESP8266 codebase, and now I understand your concern.
ESP8266 might not yield at all or might breaks any ongoing administrative progress, if delay time elapsed.
Okay. I sill investigate this problem.

**Comment by prampec** [comment]
But in this case, we might not want to use 'delay' at all, just 'yield' while waiting.

**Comment by disc0018** [comment]
I was checking the codebase too. But I am no expert.... I was not 100% sure.
But testing leads me to the same conclusion. While a very short delay a
call of a yield is not guaranteed.
With a longer delay the chance for a yield increases.

Using this theory in a test with:

void IotWebConf::delay(unsigned long m)
{
  unsigned long delayStart = millis();
  while(m > millis() - delayStart)
  {
    this->doLoop();
  }
}

void IotWebConf::doLoop()
{
  doBlink();
yield();
......

was stable without any additional yield() in my own code,
(but of course I call your doLoop() in my loop!).

So my careful conclusion is -> this could be the optimal solution?

Yours Dirk

PS. Could you implement my blinkmicrosec or something similar to get an
shorter blink.
I am so stupid with github....









Am Mi., 26. Juni 2019 um 22:15 Uhr schrieb Balázs Kelemen <
notifications@github.com>:

**Comment by disc0018** [comment]
Next problem....
I tried to call your delay from my code to improve the timing.
Similar to your idea I called it several times in a loop with
IotWebConf.delay(1).
It crashes heavyly....

Inspirated by our findings I wrote my own delay:

void mydelay(unsigned long m)
{
  unsigned long delayStart = millis();
  if (m < 11) {
    delay(m);
    return;
  } else
    yield();
  while (m >= millis() - delayStart)
  {
    loop(); -> runs my staff and calls your doloop() with yield();
  }
}

this works for me.

Yours Dirk

Am Mi., 26. Juni 2019 um 22:15 Uhr schrieb Balázs Kelemen <
notifications@github.com>:

**Comment by prampec** [comment]
Added this to version 2.2.1.

**Pull request closed without merging**
