### PR TITLE
Force ap mode

### PR DESCRIPTION
**Pull request by dopyoman**
I added the a method to force AP mode. This kind of thing could be useful if for example you to configure a device that's not a wifi network but an ESP-NOW network

### CODE REVIEW

**Comment by prampec** [comment]
Thank you for your participation! I need some days to investigate the change. Especially I do not like to pass passwords to the client. Can you please explain that part?

**Comment by dopyoman** [comment]
Looking through the lib you already have a way of resetting wifi auth via a
pin. For my use case this was inconvenient since I wanted to launch the ap
mode only to change some custom params. You see the I have built a sensor
that doesn't connect to a wifi network when running. Imagine a device that
communicates over bluetooth but you want a way to configure it.

It could also be useful for debugging.

**Comment by prampec** [comment]
Okay, okay. I understand why the forceAP is introduced.
What I do not understand, is that what is the connection between AP-only mode and publishing password to the client.

**Comment by dopyoman** [comment]
I couldn't figure out a way to not send those form fields. Ideally I would
have wanted just the custom fields to be rendered. But this was the next
best thing.

**Comment by prampec** [comment]
Still don't understand. Do you know the fact, that empty password fields are skipped by IotWebConf? (Thus if you do not fill the password fields, they will not be changed.)

**Comment by dopyoman** [comment]
I did not know that. I'll test it out again but i thought there was some
form validation there that prevented the form submission. I'll test it
tonight.

**Comment by prampec** [comment]
Introduced forceApMode() in main branch. Thank you for your cooperation. Will be available from version v2.3.1.

**Comment by ClemensGruber** [comment]
> Do you know the fact, that empty password fields are skipped by IotWebConf? (Thus if you do not fill the password fields, they will not be changed.)

I did not know this also and UI does not indicate that, so we should at least add a text that empty fiels are not overwritten with NULL or whatever. I think this is a main usability issue. While testing I hesitaded also yesterday to submit a half-full form expecting that empty fields would be saved as nothing. I would expect some dots in the field to indicate that there is a password (but could not be seen). The current empty field is bad usabilty because there is no difference between a realy empty field an a not empty input field.

**Pull request closed without merging**
