### PR TITLE
Added updateWiFiAuthInfo()

### PR DESCRIPTION
**Pull request by Webunity**
Small refactor to allow setting WiFi SSID and WiFi pwd from sketch. Usefull while developing your 'thing' and not going through the config page every time.

Sample usage:
```
void setup() {
  // ...

  boolean validConfig = iotWebConf.init();

#ifdef DEBUG
  validConfig = true;
  iotWebConf.updateWiFiAuthInfo(DEBUG_WIFI_SSID, DEBUG_WIFI_PWD);
#endif
}
```

### CODE REVIEW

**Comment by prampec** [comment]
Sounds reasonable. Please extend documentation with the information about when this method is allowed to be called. E.g. after initialization or can I call it in any state?

**Comment by Webunity** [comment]
You can call it in your setup call whenever you did a .init() first

**Comment by Webunity** [comment]
@prampec i updated the readme.md file as well.

**Comment by Webunity** [comment]
Can you merge the pull request @prampec ?

**Comment by prampec** [comment]
Please be a little bit patient. I need to free some time to perform a proper check before the merge.

**Comment by prampec** [comment]
I was struggling a lot, I'm really sorry about that, but in the end I was decided to reject this commit. Instead I have introduced the skipApStartup mode (see latest commit), where IotWebConf starts in WiFi mode immediately instead in AP mode (if possible).
Regarding to the authentication: I just did not wanted to break the security and provide a dedicated interface to store passwords in plain text. If you are clever enough, you can still access the internal parameter with e.g. getWifiPasswordParameter() (and then rewrite the values with strncpy). And with this you even have the possibility to save the configuration with configSave().

I'm not telling you, that an "updateWiFiAuthInfo()" will never exists in IotWebConf, I just say, it is not going to happen now.
If you have any questions, or comments, please let me know!

**Pull request closed without merging**
