### PR TITLE
Add mDNS update to main loop for ESP8266

### PR DESCRIPTION
**Pull request by shmick**
On ESP8266 it needs `MDNS.update()` to run in the main loop

### CODE REVIEW

**Comment by prampec** [comment]
As far as I see, the update must be called as frequently as possible in ESP8266.
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/src/LEAmDNS.h

So it should be placed inside the doLoop() method. (Must be tested before I approve!)

**Comment by shmick** [comment]
> So it should be placed inside the doLoop() method. (Must be tested before I approve!)

My code update does place it inside `doLoop()` inside of the `else if (this->_state == OnLine` statement

**Comment by prampec** [comment]
Sorry, I have missed something.

**Comment by prampec** [comment]
Thank you for your contribution.

**Pull request merged**
