### PR TITLE
add compile test with platformio by github actions

### PR DESCRIPTION
**Pull request by Rotzbua**
travis will shut down in the near future. my solution uses platformio instead of arduino ide.

### CODE REVIEW

**Comment by prampec** [comment]
However this is definitely something I would like to add, I do not like the way PIO is called here.
1. I do not think .ino files are a good idea to use in PIO.
2. MQTT does not required for all the tests.
3. Update-enabled examples also require Update library but only for esp32.

So overall I would prefer a solution, where I provide platformio.ini file for each and every example.
There are prepared scripts for the same purpose under /pio folder, I would like to see some similar approach here.

**Comment by prampec** [comment]
Basically we can also execute my prepare and build scripts in  /pio folder.

Another thing is to add a fancy indicator in the README to show people, that this branch is tested. (Like we have currently with travis.)

**Comment by prampec** [comment]
Btw. Is there any way to test a workflow?

**Comment by Rotzbua** [comment]
> I do not think .ino files are a good idea to use in PIO.

It compiles every example. Platformio works with that.

> Basically we can also execute my prepare and build scripts in /pio folder.

I am not familiar with that.

> MQTT does not required for all the tests.
> Update-enabled examples also require Update library but only for esp32.

True. Could be solved with switches like I used in the rfid lib.

> Another thing is to add a fancy indicator in the README to show people, that this branch is tested. (Like we have currently with travis.)

It is possible to add.

> Btw. Is there any way to test a workflow?

I use this script (with extension for AVR) in the rfid library.
https://github.com/miguelbalboa/rfid/blob/master/.github/workflows/test.platformio.yml
https://github.com/miguelbalboa/rfid/actions

A method to test github actions is to create an extra test repository.

**Comment by prampec** [comment]
Using to this pull request as a template I have created my own test workflow. Now available in the master branch.
Thank you for the effort!

**Comment by Rotzbua** [comment]
Glad I could help :)

**Pull request closed without merging**
